blockExoticSubdeps: true

onlyBuiltDependencies:
  - lefthook

packages:
  - "apps/*"
  - "packages/*"

publicHoistPattern:
  - "*eslint*"
  - "*prettier*"

savePrefix: ""

sideEffectsCache: false

trustPolicy: no-downgrade
